theme: jekyll-theme-minimal
title: NubemLinux-AICorp
description: Ubuntu distribution with integrated AI, corporate branding, and intelligent self-management
logo: /assets/images/logo.png
show_downloads: true
google_analytics: