name: Build NubemLinux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debootstrap \
          squashfs-tools \
          xorriso \
          grub-pc-bin \
          grub-efi-amd64-bin
    
    - name: Check scripts
      run: |
        chmod +x *.sh
        chmod +x scripts/*.sh
        bash -n build_nubemlinux.sh
        bash -n checkpoint_manager.sh
        for script in scripts/*.sh; do
          bash -n "$script"
        done
    
    - name: Test checkpoint system
      run: |
        ./checkpoint_manager.sh test
    
    - name: Validate configuration
      run: |
        source config.env
        echo "Version: $NUBEMLINUX_VERSION"
        echo "Ubuntu base: $UBUNTU_VERSION"

  build:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debootstrap \
          squashfs-tools \
          xorriso \
          grub-pc-bin \
          grub-efi-amd64-bin \
          curl \
          wget
    
    - name: Build ISO (dry-run)
      run: |
        sudo ./build_nubemlinux.sh --dry-run
    
    - name: Upload logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-logs
        path: logs/